OPTIONS (errors=0, direct=true, skip=1)
LOAD DATA 
INFILE 'manual_table_data.csv'
APPEND
INTO TABLE MANUAL_TABLE
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS (
"CONCEPT_CODE_1",
"CONCEPT_NAME_1",
"CONCEPT_ID_2",
"CONCEPT_NAME_2",
"DOMAIN_ID",
"VOCABULARY_ID",
"INVALID_REASON",
"VALID_START_DATE"	DATE "YYYY-MM-DD HH24:MI:SS",
"VALID_END_DATE"	DATE "YYYY-MM-DD HH24:MI:SS",
"PRECEDENCE",
"CONVERSION_FACTOR"
)

