OPTIONS (errors=0, direct=true, skip=1)
LOAD DATA 
INFILE 'manual_table_data.csv'
APPEND
INTO TABLE MANUAL_TABLE
FIELDS TERMINATED BY ','
# FIELDS TERMINATED BY X'9'
# FIELDS TERMINATED BY x'09'
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS (
"CONCEPT_CODE_1"        CHAR(50),
"CONCEPT_NAME_1"        CHAR(250),
"VOCABULARY_ID_1"       CHAR(20),
"INVALID_REASON_1"      CHAR(1),
"CONCEPT_CODE_2"        CHAR(50),
"CONCEPT_NAME_2"        CHAR(250),
"CONCEPT_CLASS_ID_2"    CHAR(250),
"VOCABULARY_ID_2"       CHAR(20),
"INVALID_REASON_2"      CHAR(1),
"RELATIONSHIP_ID"       CHAR(20),
"VALID_START_DATE"      DATE "YYYY-MM-DD HH24:MI:SS",
"VALID_END_DATE"        DATE "YYYY-MM-DD HH24:MI:SS",
"INVALID_REASON"        CHAR(1)
)