OPTIONS (errors=0, direct=true, skip=1)
LOAD DATA 
INFILE 'manual_table_data.csv'
APPEND
INTO TABLE MANUAL_TABLE
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS (
"CONCEPT_CODE_1"        POSITION(1:50),
"CONCEPT_NAME_1"        POSITION(51:300) CHAR,
"VOCABULARY_ID_1"       POSITION(301:320) CHAR,
"INVALID_REASON_1"      POSITION(321:321) CHAR,
"CONCEPT_CODE_2"        POSITION(322:371) CHAR,
"CONCEPT_NAME_2"        POSITION(372:621) CHAR,
"CONCEPT_CLASS_ID_2"    POSITION(622:871) CHAR,
"VOCABULARY_ID_2"       POSITION(872:891) CHAR,
"INVALID_REASON_2"      POSITION(892:892) CHAR,
"RELATIONSHIP_ID"       POSITION(893:912) CHAR,
"VALID_START_DATE"      POSITION(*) CHAR "TRUNC(TO_DATE(:VALID_START_DATE, 'YYYY-MM-DD HH24:MI:SS'))",
"VALID_END_DATE"        POSITION(*) CHAR "TRUNC(TO_DATE(:VALID_END_DATE, 'YYYY-MM-DD HH24:MI:SS'))",
"INVALID_REASON"        POSITION(*) CHAR
)