OPTIONS (errors=0, direct=true, skip=1)
LOAD DATA 
INFILE 'manual_table_data.csv'
APPEND
INTO TABLE MANUAL_TABLE
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS (
"CONCEPT_CODE_1",
"CONCEPT_NAME_1",
"VOCABULARY_ID_1",
"INVALID_REASON_1",
"CONCEPT_CODE_2",
"CONCEPT_NAME_2",
"CONCEPT_CLASS_ID_2",
"VOCABULARY_ID_2",
"INVALID_REASON_2",
"RELATIONSHIP_ID",
"VALID_START_DATE" DATE 'YYYY-MM-DD HH24:MI:SS',
"VALID_END_DATE" DATE 'YYYY-MM-DD HH24:MI:SS',
"INVALID_REASON"
)