package com.odysseusinc.net;

import com.google.common.io.Files;
import org.apache.commons.io.IOUtils;
import org.apache.commons.lang3.StringUtils;
import org.apache.http.*;
import org.apache.http.client.entity.UrlEncodedFormEntity;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.client.utils.URIBuilder;
import org.apache.http.cookie.Cookie;
import org.apache.http.entity.BufferedHttpEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.impl.cookie.BasicClientCookie;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.protocol.HttpContext;

import java.io.*;
import java.net.URISyntaxException;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Created by Sanders on 5/23/2017.
 */

public class DownloadResourceHelper {
    /**
     * Names of using cookies.
     *
     * COOKIE_JSESSIONID - session identifier on UMLS login service;
     * COOKIE_CASTGC - client authentication cookie for UMLS login service;
     * COOKIE_MOD_AUTH_CAS - client ticket-authentication cookie for UMLS download service.
     */
    public static final String COOKIE_JSESSIONID = "JSESSIONID";
    public static final String COOKIE_CASTGC = "CASTGC";
    public static final String COOKIE_CASPRIVACY = "CASPRIVACY";
    public static final String COOKIE_MOD_AUTH_CAS = "MOD_AUTH_CAS";
    public static final int NUMBER_OF_ATTEMPTS = 3;

    private CloseableHttpClient httpClient;
    private File downloadPath;
    private Properties resourceProperties;

    /**
     * Presumably "Login Ticket" parameter.
     * Used on user form during authentication, generated by UMLS login service when new session is created.
     */
    private String ltParam;

    /**
     * Class-level cookie store
     */
    private List<Cookie> localCookieStore;

    /**
     * Apache CookieStore for all cookies.
     * Isn't used because of using class-level cookie store.
     */
//    private CookieStore cookieStore;

    /**
     * Instance of Download Helper.
     */
    private static DownloadResourceHelper singleIntance;

    /**
     * Contructor
     */
    private DownloadResourceHelper() {
        this(null);
    }

    private DownloadResourceHelper(File downloadPath) {
        if (downloadPath == null || !downloadPath.exists()) {
            // Prepare temporary storage for content
            this.downloadPath = Files.createTempDir();
            this.downloadPath.deleteOnExit();
        } else
            this.downloadPath = downloadPath;

        this.localCookieStore = new ArrayList<>();

        // Load resource properties
        this.resourceProperties = new Properties();
        try {
            resourceProperties.load(new FileInputStream("./Update_UMLS.properties"));
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Create HttpClient
        this.httpClient = HttpClients.custom()
                .disableCookieManagement()
                .disableRedirectHandling()
                .setProxy(new HttpHost("127.0.0.1", 8888))
                .addInterceptorLast(new HttpRequestInterceptor() {
                    public void process(HttpRequest httpRequest, HttpContext httpContext) throws HttpException, IOException {
                        /**
                         * Remove default headers
                         */
                        httpRequest.removeHeaders("Accept");
                        httpRequest.removeHeaders("Accept-Encoding");
                        httpRequest.removeHeaders("Accept-Language");
                        httpRequest.removeHeaders("Connection");
                        httpRequest.removeHeaders("Cache-Control");
                        httpRequest.removeHeaders("Pragma");
                        httpRequest.removeHeaders("User-Agent");
                        httpRequest.removeHeaders("Referer");
                        /**
                         * Add common request headers
                         */
                        httpRequest.addHeader("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8");
                        httpRequest.addHeader("Accept-Encoding", "gzip, deflate, sdch, br");
                        httpRequest.addHeader("Accept-Language", "en-US,en;q=0.8,ru;q=0.6,uk;q=0.4");
                        httpRequest.addHeader("Cache-Control", "no-cache");
                        httpRequest.addHeader("Connection", "keep-alive");
                        httpRequest.addHeader("Pragma", "no-cache");
                        httpRequest.addHeader("Upgrade-Insecure-Requests", "1");
                        httpRequest.addHeader("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36");

                        System.out.println("##########");
                        for (Header h: httpRequest.getAllHeaders()) {
                            System.out.println(String.format("\t%s: %s", h.getName(), h.getValue()));
                        }
                        System.out.println("##########");
                    }
                }).addInterceptorLast(new HttpResponseInterceptor() {
                    public void process(HttpResponse httpResponse, HttpContext httpContext) throws HttpException, IOException {
                        /**
                         * Adding of cookie from response to class-level local storage.
                         */
                        saveClientCookie(httpResponse);
                    }
                }).build();
    }

    /**
     * Extract header value from response
     *
     * @param response
     * @param name
     * @return
     */
    private String getResponseHeaderValue(HttpResponse response, String name) {
        Header header = response.getLastHeader(name);
        if (header == null) {
            return "";
        } else {
            return header.getValue();
        }
    }

    /**
     * Convert array to List
     *
     * @param objects
     * @return
     */
    private <T> List<T> getListFromArray(T[] objects) {
        List<T> result = new ArrayList<T>();
        for (T c: objects) {
            if (c != null) {
                result.add(c);
            }
        }
        return result;
    }

    /**
     * Return all saved client's cookies.
     *
     * @return
     */
    private List<Cookie> getAllStoredCookies() {
        List<Cookie> ckList = new ArrayList<>();
        Iterator<Cookie> it = this.localCookieStore.iterator();
        while (it.hasNext()) {
            ckList.add(it.next());
        }
        return ckList;
    }

    /**
     * Get client cookie from local storage.
     *
     * @param name
     * @return
     */
    private Cookie getClientCookie(String name) {
        Cookie cookie = null;
        Iterator<Cookie> it = this.localCookieStore.iterator();
        while (it.hasNext()) {
            Cookie c = it.next();
            if (c.getName().equalsIgnoreCase(name)) {
                cookie = c;
                break;
            }
        }
        return cookie;
    }

    /**
     * Class-level Cookie Storage.
     *
     * @param response
     */
    private void saveClientCookie(HttpResponse response) {
        Header[] chArray = response.getHeaders("Set-Cookie");
        if (chArray == null)
            return;

        List<Header> chList = Arrays.asList(chArray);
        for (Header header: chList) {
            boolean skipCookie = false;
            String nameValue = header.getValue().substring(0, header.getValue().indexOf(";"));
            Cookie newCookie = new BasicClientCookie(nameValue.split("=")[0], nameValue.split("=")[1]);

            Iterator<Cookie> it = this.localCookieStore.iterator();
            while (it.hasNext()) {
                Cookie c = it.next();
                if (c.getName().equalsIgnoreCase(newCookie.getName())) {
                    skipCookie = true;
                    continue;
                }
            }
            if (!skipCookie)
                this.localCookieStore.add(newCookie);
        }
    }

    /**
     * Add multiple cookies to response.
     *
     * @param request
     * @param cookies
     * @return
     */
    private HttpRequest setRequestCookies(HttpRequest request, List<Cookie> cookies) {
        if (cookies == null || cookies.isEmpty())
            return request;

        StringBuilder sb = new StringBuilder();
        for (Cookie c: cookies) {
            if (c != null) {
                if (sb.toString().length() != 0)
                    sb.append(";");
                sb.append(String.format("%s=%s", c.getName(), c.getValue()));
            }
        }
        if (sb.length() > 0)
            request.addHeader("Cookie", sb.toString());
        return request;
    }

    /**
     * Convert parameter's map to name-value format, for convenient usage for Apache's classes.
     *
     * @param params
     * @return
     */
    private List<NameValuePair> toMapNameValuePairs(Map<String, String> params) {
        List<NameValuePair> nvpList = new ArrayList<>();
        Iterator<Map.Entry<String, String>> it = params.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry<String, String> entry = it.next();
            String name = entry.getKey();
            String value = entry.getValue();
            if (StringUtils.isNotBlank(name) && StringUtils.isNoneBlank(value))
                nvpList.add(new BasicNameValuePair(name, value));
        }
        return nvpList;
    }

    /**
     * Prepare GET request.
     *
     * @param url
     * @return
     * @throws IOException
     * @throws URISyntaxException
     */
    private HttpGet prepareGet(String url) throws IOException, URISyntaxException {
        return prepareGet(url, null, null);
    }

    /**
     * Prepare GET request with adding multiple cookies.
     *
     * @param url
     * @param cookies
     * @return
     * @throws IOException
     * @throws URISyntaxException
     */
    private HttpGet prepareGet(String url, List<Cookie> cookies) throws IOException, URISyntaxException {
        return prepareGet(url, null, cookies);
    }

    /**
     * Prepare parametrised GET request with adding multiple cookies.
     *
     * @param url
     * @param params
     * @param cookies
     * @return
     * @throws IOException
     * @throws URISyntaxException
     */
    private HttpGet prepareGet(String url, Map<String, String> params, List<Cookie> cookies) throws IOException, URISyntaxException {
        if (params != null && !params.isEmpty()) {
            URIBuilder uriBuilder = new URIBuilder(url);
            List<NameValuePair> pairList = toMapNameValuePairs(params);
            uriBuilder.addParameters(pairList);
            url = uriBuilder.toString();
        }
        HttpGet request = new HttpGet(url);
        setRequestCookies(request, cookies);
        return request;
    }

    /**
     * Prepare parametrised POST request
     *
     * @param url
     * @param params
     * @return
     * @throws IOException
     * @throws URISyntaxException
     */
    private HttpPost preparePost(String url, Map<String, String> params) throws IOException, URISyntaxException {
        return preparePost(url, params, null);
    }

    /**
     * Prepare parametrised POST request with adding multiple cookies.
     *
     * @param url
     * @param params
     * @param cookies
     * @return
     * @throws IOException
     * @throws URISyntaxException
     */
    private HttpPost preparePost(String url, Map<String, String> params, List<Cookie> cookies) throws IOException, URISyntaxException {
        HttpPost request = new HttpPost(url);
        if (params != null && !params.isEmpty()) {
            List<NameValuePair> pairList = toMapNameValuePairs(params);
            request.setEntity(new UrlEncodedFormEntity(pairList));
        }
        setRequestCookies(request, cookies);
        return request;
    }

    /**
     * Return resource property value by it's name
     *
     * @param name
     * @return
     */
    public static String getPropertyByName(String name) {
        return getDownloadResourceHelper().resourceProperties.getProperty(name);
    }

    /**
     * Get instance
     *
     * @return
     */
    public static DownloadResourceHelper getDownloadResourceHelper() {
        if (singleIntance == null) {
            singleIntance = new DownloadResourceHelper();
        }
        return singleIntance;
    }

    public static DownloadResourceHelper getDownloadResourceHelper(File downloadPath) {
        if (singleIntance == null) {
            singleIntance = new DownloadResourceHelper(downloadPath);
        }
        return singleIntance;
    }

    public String getDownloadPath() {
        return this.downloadPath.getPath();
    }

    public String repeatableDownloadResourceUmls(String loginUrl, String userName, String password, String fileUrl, String fileName, String packageDescription) throws IOException {
        /**
         * Try three times redownload if error occurs
         */
        return downloadResourceUmls(loginUrl, userName, password, fileUrl, fileName, packageDescription,true, NUMBER_OF_ATTEMPTS);
    }

    public String downloadResourceUmls(String loginUrl, String userName, String password, String fileUrl, String fileName, String packageDescription) throws IOException {
        return downloadResourceUmls(loginUrl, userName, password, fileUrl, fileName, packageDescription, false, 0);
    }

    public String repeatableDownloadResourceUmlsFull(String fileUrl, String userName, String password, String fileName, String packageDescription) throws IOException {
        /**
         * Try three times redownload if error occurs
         */
        return downloadResourceUmlsFull(fileUrl, userName, password, fileName, packageDescription,true, NUMBER_OF_ATTEMPTS);
    }

    // Just login UMLS
    private boolean loginUmls(String loginUrl, String userName, String password) throws IOException {
        CloseableHttpResponse response = null;
        try {
            HttpGet request = prepareGet(loginUrl);
            response = httpClient.execute(request);

            int responseCode = response.getStatusLine().getStatusCode();
            if (responseCode != HttpStatus.SC_OK) {
                throw new HttpException(String.format("Unable to login UMLS service\n%s", response.getStatusLine()));
            } else
                return true;
        } catch (Exception e) {
            System.out.println("Error occurs: " + e.getMessage());
            e.printStackTrace();
            return false;
        } finally {
            if (response != null) {
                response.close();
            }
        }
    }

    public String repeatableDownloadUmls(String fileUrl, String fileName, String packageDescription) throws IOException {
        return downloadUmls(fileUrl, fileName, packageDescription, true, NUMBER_OF_ATTEMPTS);
    }

    // Just download UMLS routine
    public String downloadUmls(String fileUrl, String fileName, String packageDescription, boolean isTryRedownload, int numberOfTries) throws IOException {
        CloseableHttpResponse response = null;
        OutputStream outputStream = null;
        try {
            List<Cookie> cookies = new ArrayList<>();
//            cookies.addAll(getAllStoredCookies());
//            cookies.add(getClientCookie(COOKIE_CASPRIVACY));
            cookies.add(getClientCookie(COOKIE_MOD_AUTH_CAS));
            System.out.println("\nStep 4. Get url: " + fileUrl);
            HttpGet request = prepareGet(fileUrl, cookies);

            System.out.println("!!!!! Request headers:");
            List<Header> lHeader = Arrays.asList(request.getAllHeaders());
            for (Header h: lHeader) {
                System.out.println(String.format("\t%s: %s", h.getName(), h.getValue()));
            }

            response = httpClient.execute(request);

            System.out.println("\n!!!!! Response:");
            System.out.println("\tresponse.getStatusLine():" + response.getStatusLine());
            System.out.println("\tcontent-type:" + getResponseHeaderValue(response, "Content-Type"));
            System.out.println("\tlocation:" + getResponseHeaderValue(response, "Location"));
            System.out.println("\tset-cookie:");
            List<Header> listHeaders = Arrays.asList(response.getHeaders("Set-Cookie"));
            for (Header h: listHeaders) {
                System.out.println("\t\t" + h.getValue());
            }
            System.out.println("\tcontent-disposition:" + getResponseHeaderValue(response, "Content-Disposition"));

            int responseCode = response.getStatusLine().getStatusCode();
            if (responseCode != HttpStatus.SC_OK) {
                numberOfTries--;
                if (isTryRedownload && numberOfTries >= 0) {
                    try {
                        if (response != null) {
                            response.close();
                        }
                    } catch (IOException ioe) {}
                    System.out.println(String.format("Attention!\nThere is some problem of content downloading: %s.\nTry again, attempt %d of %d....", response.getStatusLine(), NUMBER_OF_ATTEMPTS - numberOfTries, NUMBER_OF_ATTEMPTS));
                    return downloadUmls(fileUrl, fileName, packageDescription, isTryRedownload, numberOfTries);
                } else {
                    throw new HttpException(String.format("Unable to download %s\n%s", packageDescription, response.getStatusLine()));
                }
            } else if (getResponseHeaderValue(response, "Content-Type").indexOf("zip") < 0) {
                throw new HttpException(String.format("%s is not a ZIP archive", packageDescription));
            }

            // Eval downloaded file name
            String contentDisposition = getResponseHeaderValue(response, "Content-Disposition");
            if (contentDisposition.length() > 0)
                fileName = contentDisposition.substring(contentDisposition.lastIndexOf("filename") + 9).replace("\"", "").replace(";", "");
            String filePath = String.format("%s%s%s", this.downloadPath.getPath(), File.separator, fileName);

            String contentLength = getResponseHeaderValue(response,"Content-Length");
            System.out.println(String.format("Downloaded '%s' file with %s bytes", fileName, contentLength));

            // Save file to stream
            BufferedHttpEntity bufEntity = new BufferedHttpEntity(response.getEntity());
            outputStream = new FileOutputStream(new File(filePath));
            IOUtils.copyLarge(bufEntity.getContent(), outputStream);
            outputStream.flush();

        } catch (Exception e) {
            System.out.println("Error occurs: " + e.getMessage());
            e.printStackTrace();
        } finally {
            if (response != null) {
                response.close();
            }

            if (outputStream != null) {
                outputStream.close();
            }
        }
        return fileName;
    }

    // Login and download resource
    public String downloadResourceUmlsFull(String fileUrl,String userName, String password, String fileName, String packageDescription, boolean isTryRedownload, int numberOfTries) throws IOException {
        this.localCookieStore.clear();
        CloseableHttpResponse response = null;
        // REQUEST 1
        // Just get JSESSION cookie
        try {
            System.out.println("\nStep 1. Get url: " + fileUrl);
            HttpGet request = prepareGet(fileUrl);

            System.out.println("!!!!! Request headers:");
            List<Header> lHeader = Arrays.asList(request.getAllHeaders());
            for (Header h: lHeader) {
                System.out.println(String.format("\t%s: %s", h.getName(), h.getValue()));
            }

            response = httpClient.execute(request);

            // Buffer response content
            BufferedHttpEntity bufEntity = new BufferedHttpEntity(response.getEntity());
            StringWriter writer = new StringWriter();
            IOUtils.copy(bufEntity.getContent(), writer, StandardCharsets.UTF_8);
            String responseBody = writer.toString().trim();

            System.out.println("\n!!!!! Response:");
            System.out.println("\tresponse.getStatusLine():" + response.getStatusLine());
            System.out.println("\tcontent-type:" + getResponseHeaderValue(response, "Content-Type"));
            System.out.println("\tlocation:" + getResponseHeaderValue(response, "Location"));
            System.out.println("\tset-cookie:");
            List<Header> listHeaders = Arrays.asList(response.getHeaders("Set-Cookie"));
            for (Header h: listHeaders) {
                System.out.println("\t\t" + h.getValue());
            }
            System.out.println("\tcontent-disposition:" + getResponseHeaderValue(response, "Content-Disposition"));
            System.out.println("\tresponseBody:" + responseBody);

            // Remember dynamically generated presumably "Login Ticket" form parameter
            Pattern ltPattern = Pattern.compile("name=\"lt\" value=\"(\\w+)\"");
            Matcher m = ltPattern.matcher(responseBody);
            while (m.find()) {
                this.ltParam = m.group(1);
            }
        } catch (Exception e) {
            System.out.println("Error occurs: " + e.getMessage());
            e.printStackTrace();
        } finally {
            if (response != null) {
                response.close();
            }
        }

        // REQUEST 2
        // Login to UMLS
        System.out.println("Login UMLS service...");
        try {
            Map<String, String> params = new HashMap<String, String>();
            params.put("username", userName);
            params.put("password", password);
            params.put("lt", this.ltParam);
            params.put("_eventId", "submit");
            params.put("submit", "Sign In");
            List<Cookie> cookies = new ArrayList<>();
//            cookies.addAll(getAllStoredCookies());
            cookies.add(getClientCookie(COOKIE_JSESSIONID));
            System.out.println("\nStep 2. Get url: " + fileUrl);
            HttpPost request = preparePost(fileUrl, params, cookies);
            request.addHeader("Content-Type", "application/x-www-form-urlencoded");

            System.out.println("!!!!! Request headers:");
            List<Header> lHeader = Arrays.asList(request.getAllHeaders());
            for (Header h: lHeader) {
                System.out.println(String.format("\t%s: %s", h.getName(), h.getValue()));
            }

            response = httpClient.execute(request);

            // Buffer response content
            BufferedHttpEntity bufEntity = new BufferedHttpEntity(response.getEntity());
            StringWriter writer = new StringWriter();
            IOUtils.copy(bufEntity.getContent(), writer, StandardCharsets.UTF_8);
            String responseBody = writer.toString().trim();

            System.out.println("\n!!!!! Response:");
            System.out.println("\tresponse.getStatusLine():" + response.getStatusLine());
            System.out.println("\tcontent-type:" + getResponseHeaderValue(response, "Content-Type"));
            System.out.println("\tlocation:" + getResponseHeaderValue(response, "Location"));
            System.out.println("\tset-cookie:");
            List<Header> listHeaders = Arrays.asList(response.getHeaders("Set-Cookie"));
            for (Header h: listHeaders) {
                System.out.println("\t\t" + h.getValue());
            }
            System.out.println("\tcontent-disposition:" + getResponseHeaderValue(response, "Content-Disposition"));
            System.out.println("\tresponseBody:" + responseBody);

            /**
             * Get URL for further processing
             */
            String locationHeaderValue = getResponseHeaderValue(response, "Location");
            if (StringUtils.isNotBlank(locationHeaderValue))
                fileUrl = locationHeaderValue;
        } catch (Exception e) {
            System.out.println("Exception occurs: " + e.getMessage());
            e.printStackTrace();
        } finally {
            if (response != null)
                response.close();
        }

        // REQUEST 3
        // Authorize on download service with ticket
        try {
//            List<Cookie> cookies = new ArrayList<>();
//            cookies.addAll(getAllStoredCookies());
            System.out.println("\nStep 3. Get url: " + fileUrl);
            HttpGet request = prepareGet(fileUrl);

            System.out.println("!!!!! Request headers:");
            List<Header> lHeader = Arrays.asList(request.getAllHeaders());
            for (Header h: lHeader) {
                System.out.println(String.format("\t%s: %s", h.getName(), h.getValue()));
            }

            response = httpClient.execute(request);

            // Buffer response content
            BufferedHttpEntity bufEntity = new BufferedHttpEntity(response.getEntity());
            StringWriter writer = new StringWriter();
            IOUtils.copy(bufEntity.getContent(), writer, StandardCharsets.UTF_8);
            String responseBody = writer.toString().trim();

            System.out.println("\n!!!!! Response:");
            System.out.println("\tresponse.getStatusLine():" + response.getStatusLine());
            System.out.println("\tcontent-type:" + getResponseHeaderValue(response, "Content-Type"));
            System.out.println("\tlocation:" + getResponseHeaderValue(response, "Location"));
            System.out.println("\tset-cookie:");
            List<Header> listHeaders = Arrays.asList(response.getHeaders("Set-Cookie"));
            for (Header h: listHeaders) {
                System.out.println("\t\t" + h.getValue());
            }
            System.out.println("\tcontent-disposition:" + getResponseHeaderValue(response, "Content-Disposition"));
            System.out.println("\tresponseBody:" + responseBody);

            /**
             * Get URL for further processing
             */
            String locationHeaderValue = getResponseHeaderValue(response, "Location");
            if (StringUtils.isNotBlank(locationHeaderValue))
                fileUrl = locationHeaderValue;
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (response != null)
                response.close();
        }

        // REQUEST 4
        // Download resource
        return downloadUmls(fileUrl, fileName, packageDescription, isTryRedownload, numberOfTries);
    }

    // Login and download resource
    public String downloadResourceUmls(String loginUrl, String userName, String password, String fileUrl, String fileName, String packageDescription, boolean isTryRedownload, int numberOfTries) throws IOException {
        this.localCookieStore.clear();
        CloseableHttpResponse response = null;
        // REQUEST 1
        // Just to get first JSESSION cookie
        try {
            System.out.println("\nStep 1. Get url: " + loginUrl);
            HttpGet request = prepareGet(loginUrl);

            System.out.println("!!!!! Request headers:");
            List<Header> lHeader = Arrays.asList(request.getAllHeaders());
            for (Header h: lHeader) {
                System.out.println(String.format("\t%s: %s", h.getName(), h.getValue()));
            }

            response = httpClient.execute(request);

            // Buffer response content
            BufferedHttpEntity bufEntity = new BufferedHttpEntity(response.getEntity());
            StringWriter writer = new StringWriter();
            IOUtils.copy(bufEntity.getContent(), writer, StandardCharsets.UTF_8);
            String responseBody = writer.toString().trim();

            System.out.println("\n!!!!! Response:");
            System.out.println("\tresponse.getStatusLine():" + response.getStatusLine());
            System.out.println("\tcontent-type:" + getResponseHeaderValue(response, "Content-Type"));
            System.out.println("\tlocation:" + getResponseHeaderValue(response, "Location"));
            System.out.println("\tset-cookie:");
            List<Header> listHeaders = Arrays.asList(response.getHeaders("Set-Cookie"));
            for (Header h: listHeaders) {
                System.out.println("\t\t" + h.getValue());
            }
            System.out.println("\tcontent-disposition:" + getResponseHeaderValue(response, "Content-Disposition"));
            System.out.println("\tresponseBody:" + responseBody);

            // Remember dynamically generated presumably "Login Ticket" form parameter
            Pattern ltPattern = Pattern.compile("name=\"lt\" value=\"(\\w+)\"");
            Matcher m = ltPattern.matcher(responseBody);
            while (m.find()) {
                this.ltParam = m.group(1);
            }
        } catch (Exception e) {
            System.out.println("Error occurs: " + e.getMessage());
            e.printStackTrace();
        } finally {
            if (response != null) {
                response.close();
            }
        }

        // REQUEST 2
        // Login
        System.out.println("Login UMLS service...");
        try {
            Map<String, String> params = new HashMap<String, String>();
            params.put("username", userName);
            params.put("password", password);
            params.put("lt", this.ltParam);
            params.put("_eventId", "submit");
            params.put("submit", "Sign In");
            List<Cookie> cookies = new ArrayList<>();
//            cookies.addAll(getAllStoredCookies());
            cookies.add(getClientCookie(COOKIE_JSESSIONID));
            System.out.println("\nStep 2. Get url: " + fileUrl);
            HttpPost request = preparePost(fileUrl, params, cookies);
            request.addHeader("Content-Type", "application/x-www-form-urlencoded");

            System.out.println("!!!!! Request headers:");
            List<Header> lHeader = Arrays.asList(request.getAllHeaders());
            for (Header h: lHeader) {
                System.out.println(String.format("\t%s: %s", h.getName(), h.getValue()));
            }

            response = httpClient.execute(request);

            // Buffer response content
            BufferedHttpEntity bufEntity = new BufferedHttpEntity(response.getEntity());
            StringWriter writer = new StringWriter();
            IOUtils.copy(bufEntity.getContent(), writer, StandardCharsets.UTF_8);
            String responseBody = writer.toString().trim();

            System.out.println("\n!!!!! Response:");
            System.out.println("\tresponse.getStatusLine():" + response.getStatusLine());
            System.out.println("\tcontent-type:" + getResponseHeaderValue(response, "Content-Type"));
            System.out.println("\tlocation:" + getResponseHeaderValue(response, "Location"));
            System.out.println("\tset-cookie:");
            List<Header> listHeaders = Arrays.asList(response.getHeaders("Set-Cookie"));
            for (Header h: listHeaders) {
                System.out.println("\t\t" + h.getValue());
            }
            System.out.println("\tcontent-disposition:" + getResponseHeaderValue(response, "Content-Disposition"));
            System.out.println("\tresponseBody:" + responseBody);

            /**
             * Get URL for further processing
             */
            String locationHeaderValue = getResponseHeaderValue(response, "Location");
            if (StringUtils.isNotBlank(locationHeaderValue))
                fileUrl = locationHeaderValue;
        } catch (Exception e) {
            System.out.println("Exception occurs: " + e.getMessage());
            e.printStackTrace();
        } finally {
            if (response != null)
                response.close();
        }

        // Skip this step if ticket login is available after login
        // REQUEST 3
        // Get ticket for requested resource
        try {
            List<Cookie> cookies = new ArrayList<>();
//            cookies.addAll(getAllStoredCookies());
            cookies.add(getClientCookie(COOKIE_JSESSIONID));
            cookies.add(getClientCookie(COOKIE_CASTGC));
            System.out.println("\nStep 3. Get url: " + fileUrl);
            HttpGet request = prepareGet(fileUrl, cookies);

            System.out.println("!!!!! Request headers:");
            List<Header> lHeader = Arrays.asList(request.getAllHeaders());
            for (Header h: lHeader) {
                System.out.println(String.format("\t%s: %s", h.getName(), h.getValue()));
            }

            response = httpClient.execute(request);

            // Buffer response content
            BufferedHttpEntity bufEntity = new BufferedHttpEntity(response.getEntity());
            StringWriter writer = new StringWriter();
            IOUtils.copy(bufEntity.getContent(), writer, StandardCharsets.UTF_8);
            String responseBody = writer.toString().trim();

            System.out.println("\n!!!!! Response:");
            System.out.println("\tresponse.getStatusLine():" + response.getStatusLine());
            System.out.println("\tcontent-type:" + getResponseHeaderValue(response, "Content-Type"));
            System.out.println("\tlocation:" + getResponseHeaderValue(response, "Location"));
            System.out.println("\tset-cookie:");
            List<Header> listHeaders = Arrays.asList(response.getHeaders("Set-Cookie"));
            for (Header h: listHeaders) {
                System.out.println("\t\t" + h.getValue());
            }
            System.out.println("\tcontent-disposition:" + getResponseHeaderValue(response, "Content-Disposition"));
            System.out.println("\tresponseBody:" + responseBody);

            /**
             * Get URL for further processing
             */
            String locationHeaderValue = getResponseHeaderValue(response, "Location");
            if (StringUtils.isNotBlank(locationHeaderValue))
                fileUrl = locationHeaderValue;
        } catch (Exception e) {
            System.out.println("Error occurs: " + e.getMessage());
            e.printStackTrace();
        } finally {
            if (response != null)
                response.close();
        }
        // REQUEST 4
        // Authorize on download service
        try {
//            List<Cookie> cookies = new ArrayList<>();
//            cookies.addAll(getAllStoredCookies());
            System.out.println("\nStep 4. Get url: " + fileUrl);
            HttpGet request = prepareGet(fileUrl);

            System.out.println("!!!!! Request headers:");
            List<Header> lHeader = Arrays.asList(request.getAllHeaders());
            for (Header h: lHeader) {
                System.out.println(String.format("\t%s: %s", h.getName(), h.getValue()));
            }

            response = httpClient.execute(request);

            // Buffer response content
            BufferedHttpEntity bufEntity = new BufferedHttpEntity(response.getEntity());
            StringWriter writer = new StringWriter();
            IOUtils.copy(bufEntity.getContent(), writer, StandardCharsets.UTF_8);
            String responseBody = writer.toString().trim();

            System.out.println("\n!!!!! Response:");
            System.out.println("\tresponse.getStatusLine():" + response.getStatusLine());
            System.out.println("\tcontent-type:" + getResponseHeaderValue(response, "Content-Type"));
            System.out.println("\tlocation:" + getResponseHeaderValue(response, "Location"));
            System.out.println("\tset-cookie:");
            List<Header> listHeaders = Arrays.asList(response.getHeaders("Set-Cookie"));
            for (Header h: listHeaders) {
                System.out.println("\t\t" + h.getValue());
            }
            System.out.println("\tcontent-disposition:" + getResponseHeaderValue(response, "Content-Disposition"));
            System.out.println("\tresponseBody:" + responseBody);

            /**
             * Get URL for further processing
             */
            String locationHeaderValue = getResponseHeaderValue(response, "Location");
            if (StringUtils.isNotBlank(locationHeaderValue))
                fileUrl = locationHeaderValue;
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (response != null)
                response.close();
        }

        // REQUEST 5
        // Download resource
        return downloadUmls(fileUrl, fileName, packageDescription, isTryRedownload, numberOfTries);
    }


    public boolean loginLoinc(String loginUrl, String userName, String password) throws IOException {
        CloseableHttpResponse response = null;
        // Login LOINC services
        try {
            Map<String, String> params = new HashMap<String, String>();
            params.put("log", userName);
            params.put("pwd", password);
            params.put("wp-submit", "Log In");
            HttpPost request = preparePost(loginUrl, params);
            response = httpClient.execute(request);

            return true;
        } catch (Exception e) {
            System.out.println("Error occurs: " + e.getMessage());
            e.printStackTrace();
            return false;
        } finally {
            if (response != null) {
                response.close();
            }
        }
    }

    public String downloadResourceLoinc(String fileUrl, String fileName, String packageDescription) throws IOException {
        return downloadResourceLoinc(fileUrl, fileName, packageDescription, false, 0);
    }

    public String repeatableDownloadResourceLoinc(String fileUrl, String fileName, String packageDescription) throws IOException {
        /**
         * Try three times redownload if error occurs
         */
        return downloadResourceLoinc(fileUrl, fileName, packageDescription, true, NUMBER_OF_ATTEMPTS);
    }

    public String downloadResourceLoinc(String fileUrl, String fileName, String packageDescription, boolean isTryRedownload, int numberOfTries) throws IOException {
        OutputStream outputStream = null;
        CloseableHttpResponse response = null;
        try {
            Map<String, String> params = new HashMap<String, String>();
            params.put("tc_accepted", "1");
            params.put("tc_submit", "Download");
            List<Cookie> cookies = getAllStoredCookies();
            HttpPost request = preparePost(fileUrl, params, cookies);
            response = httpClient.execute(request);

            int responseCode = response.getStatusLine().getStatusCode();
            if (responseCode != HttpStatus.SC_OK) {
                numberOfTries--;
                if (isTryRedownload && numberOfTries > 0) {
                    try {
                        if (response != null) {
                            response.close();
                        }
                    } catch (IOException ioe) {}
                    System.out.println(String.format("Attention!\nThere is some problem of content downloading: %s.\nTry again, attempt %d of %d....", response.getStatusLine(), NUMBER_OF_ATTEMPTS - numberOfTries, NUMBER_OF_ATTEMPTS));
                    return downloadResourceLoinc(fileUrl, fileName, packageDescription, isTryRedownload, numberOfTries);
                } else {
                    throw new HttpException(String.format("Unable to download %s\n%s", packageDescription, response.getStatusLine()));
                }
            } else if (getResponseHeaderValue(response, "Content-Type").indexOf("zip") < 0) {
                throw new HttpException(String.format("%s is not a ZIP archive", packageDescription));
            }

            // Buffer response content
            BufferedHttpEntity bufEntity = new BufferedHttpEntity(response.getEntity());
            StringWriter writer = new StringWriter();
            IOUtils.copy(bufEntity.getContent(), writer, StandardCharsets.UTF_8);
            String responseBody = writer.toString().trim();

            // Eval downloaded file name
            String contentDisposition = getResponseHeaderValue(response, "Content-Disposition");
            if (contentDisposition.length() > 0) {
                fileName = contentDisposition.substring(contentDisposition.lastIndexOf("filename") + 9).replace("\"", "").replace(";", "");
            }
            String filePath = String.format("%s%s%s", this.downloadPath.getPath(), File.separator, fileName);

            String contentLength = getResponseHeaderValue(response,"Content-Length");
            System.out.println(String.format("Downloaded '%s' file with %s bytes", fileName, contentLength));

            // Save file to stream
            outputStream = new FileOutputStream(new File(filePath));
            IOUtils.copy(bufEntity.getContent(), outputStream);
            outputStream.flush();

        } catch (Exception e) {
            System.out.println("Error occurs: " + e.getMessage());
            e.printStackTrace();
        } finally {
            if (response != null) {
                response.close();
            }
            if (outputStream != null) {
                outputStream.close();
            }
        }
        return fileName;
    }

    public static void testDownloadLOINC(DownloadResourceHelper downloadHelper) throws IOException {
        // Login LOINC service
        System.out.println("\nLogin LOINC service...");
        String url = getPropertyByName("downloadUpdatePack.loinc.loginUrl");
        String userName = getPropertyByName("downloadUpdatePack.loinc.username");
        String password = getPropertyByName("downloadUpdatePack.loinc.password");
        downloadHelper.loginLoinc(url, userName, password);

        // Download 'Full Set' package
        String packageDescription = getPropertyByName("downloadUpdatePack.fullSet.description");
        System.out.println(String.format("\nDownload %s...", packageDescription));
        String fileUrl = getPropertyByName("downloadUpdatePack.fullSet.fileUrl");
        String defaultFileName = getPropertyByName("downloadUpdatePack.fullSet.fileName");
        downloadHelper.downloadResourceLoinc(fileUrl, defaultFileName, packageDescription);

        // Download 'Multiaxial Hierarchy' package
        packageDescription = getPropertyByName("downloadUpdatePack.multiaxialHierarchy.description");
        System.out.println(String.format("\nDownload %s...", packageDescription));
        fileUrl = getPropertyByName("downloadUpdatePack.multiaxialHierarchy.fileUrl");
        defaultFileName = getPropertyByName("downloadUpdatePack.multiaxialHierarchy.fileName");
        downloadHelper.downloadResourceLoinc(fileUrl, defaultFileName, packageDescription);

        // Download 'Panels and Forms' package
        packageDescription = getPropertyByName("downloadUpdatePack.panelsForms.description");
        System.out.println(String.format("\nDownload %s...", packageDescription));
        fileUrl = getPropertyByName("downloadUpdatePack.panelsForms.fileUrl");
        defaultFileName = getPropertyByName("downloadUpdatePack.panelsForms.fileName");
        downloadHelper.downloadResourceLoinc(fileUrl, defaultFileName, packageDescription);

        // Download 'CT Expression Association' package
        packageDescription = getPropertyByName("downloadUpdatePack.expressionAssociation.description");
        System.out.println(String.format("\nDownload %s...", packageDescription));
        fileUrl = getPropertyByName("downloadUpdatePack.expressionAssociation.fileUrl");
        defaultFileName = getPropertyByName("downloadUpdatePack.expressionAssociation.fileName");
        downloadHelper.downloadResourceLoinc(fileUrl, defaultFileName, packageDescription);

        // Login and download from UMLS service
        System.out.println("\nLogin and download from UMLS service...");
        packageDescription = getPropertyByName("downloadUpdatePack.cptMappings.description");
        url = getPropertyByName("downloadUpdatePack.umls.loginUrl");
        userName = getPropertyByName("downloadUpdatePack.umls.username");
        password = getPropertyByName("downloadUpdatePack.umls.password");
        fileUrl = getPropertyByName("downloadUpdatePack.cptMappings.fileUrl");
        defaultFileName = getPropertyByName("downloadUpdatePack.cptMappings.fileName");
        downloadHelper.downloadResourceUmls(url, userName, password, fileUrl, defaultFileName, packageDescription);
    }

    public static void testDownloadUMLS(DownloadResourceHelper downloadHelper) throws IOException {
        /* Downloading file */
        // Start action checkpoint
        long timeStart = System.currentTimeMillis();

        /****************************************************
         * Login 'UMLS' service
         * **************************************************/
        /****************************************************
         * Download 'UMLS' package
         * **************************************************/

        String loginUrl = getPropertyByName("downloadUpdatePack.umls.loginUrl");
        String userName = getPropertyByName("downloadUpdatePack.umls.username");
        String password = getPropertyByName("downloadUpdatePack.umls.password");
        String packageDescription = getPropertyByName("downloadUpdatePack.umlsFull.description");
        System.out.println("Downloading " + packageDescription);
        String fileUrl = getPropertyByName("downloadUpdatePack.umlsFull.fileUrl");
        String defaultFileName = getPropertyByName("downloadUpdatePack.umlsFull.fileName");
        String downloadedFileName = downloadHelper.repeatableDownloadResourceUmls(loginUrl, userName, password, fileUrl, defaultFileName, packageDescription);
        System.out.println("Downloaded file: " + downloadedFileName);

        System.out.println("Downloaded complete.\nUpdate packages are saved to the: " + downloadHelper.getDownloadPath());

        // Finish action checkpoint
        long timeFinish = System.currentTimeMillis();
        long timeElapsed = (timeFinish - timeStart) / 1000;
        System.out.println("Time elapsed: " + timeElapsed + " seconds.");

        System.out.println("*** " + packageDescription + " action done ***");
    }

    public static void testDownloadUMLSFull(DownloadResourceHelper downloadHelper) throws IOException {
        /* Downloading file */
        // Start action checkpoint
        long timeStart = System.currentTimeMillis();

        /****************************************************
         * Login  and download 'Full UMLS' package
         * **************************************************/

        String fileUrl = getPropertyByName("downloadUpdatePack.umlsFull.fileUrl");
        String userName = getPropertyByName("downloadUpdatePack.umls.username");
        String password = getPropertyByName("downloadUpdatePack.umls.password");
        String packageDescription = getPropertyByName("downloadUpdatePack.umlsFull.description");
        System.out.println("Downloading " + packageDescription);
        String defaultFileName = getPropertyByName("downloadUpdatePack.umlsFull.fileName");
        String downloadedFileName = downloadHelper.repeatableDownloadResourceUmlsFull(fileUrl, userName, password, defaultFileName, packageDescription);
        System.out.println("Downloaded file: " + downloadedFileName);

        System.out.println("Downloaded complete.\nUpdate packages are saved to the: " + downloadHelper.getDownloadPath());

        // Finish action checkpoint
        long timeFinish = System.currentTimeMillis();
        long timeElapsed = (timeFinish - timeStart) / 1000;
        System.out.println("Time elapsed: " + timeElapsed + " seconds.");

        System.out.println("*** " + packageDescription + " action done ***");
    }

    public static void main(String[] args) throws IOException {
        DownloadResourceHelper downloadHelper = DownloadResourceHelper.getDownloadResourceHelper();
        //testDownloadLOINC (downloadHelper);

        //testDownloadUMLS(downloadHelper);

        testDownloadUMLSFull(downloadHelper);
    }

}