OPTIONS (errors=0, direct=true, skip=1)
LOAD DATA 
INFILE 'manual_table_data.csv'
APPEND
INTO TABLE MANUAL_TABLE
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS (
"CONCEPT_CODE_1" POSITION(1:255) CHAR,
"CONCEPT_NAME_1" POSITION(256:511) CHAR,
"CONCEPT_ID_2" POSITION(512:550) INTEGER,
"CONCEPT_NAME_2" POSITION(551:806) CHAR,
"DOMAIN_ID" POSITION(807:827) CHAR,
"VOCABULARY_ID" POSITION(828:848) CHAR,
"INVALID_REASON" POSITION(849:850) CHAR,
"VALID_START_DATE" POSITION(*) DATE "YYYY-MM-DD HH24:MI:SS",
"VALID_END_DATE"   POSITION(*) DATE "YYYY-MM-DD HH24:MI:SS",
"PRECEDENCE" POSITION(*) INTEGER "TO_NUMBER(:PRECEDENCE, '999,999,999,999')",
"CONVERSION_FACTOR" POSITION(*) FLOAT "TO_NUMBER(:CONVERSION_FACTOR, '999,999,999.9999')"
)

